package: './package.json'
parallel: false
recursive: false
#reporter: 'spec'
timeout: '6000'
reporter : 'mochawesome'
require: 'mochawesome/register'
reporter-option: [
   reportFilename: 'mochawesome-reports',
   quiet: true,
   html: true
]
file:
  - './test/setup.js'
  - './fixtures.cjs'
extension: ['js', 'cjs', 'mjs']