package: './package.json'
parallel: true
recursive: false
#reporter: 'spec'
timeout: '6000'
reporter : 'mochawesome'
require: 'mochawesome/register'
reporter-option: [
   reportFilename: 'mochawesome-reports',
   quiet: true,
   html: true
]

extension: ['js', 'cjs', 'mjs']